import News from "@/components/News/News";
import Head from "next/head";
import { gql, request } from "graphql-request";

export type dataType = {
  id: string;
  title: string;
  date: string;
  banner: {
    url: string;
  };
  description: {
    raw: any;
  };
  slug: string;
};

export type props = {
  data: dataType[];
};

const Newsroom: React.FC<props> = ({ data }) => {
  return (
    <>
      <Head>
        <title>VSFG - NewsRoom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <News data={data} />
    </>
  );
};

export default Newsroom;

export const getStaticProps = async () => {
  const endpoint =
    "https://api-ap-south-1.hygraph.com/v2/cldqz7cus35l401um0na00i10/master";

  const query = gql`
    query getNewsContent {
      newsContents {
        id
        date
        title
        description {
          raw
        }
        banner {
          url
        }
        slug
      }
    }
  `;

  const data = await request(endpoint, query);

  return {
    props: { data: data.newsContents },
    revalidate: 10,
  };
};
