import Policy from "@/components/Policy/Policy";
import Head from "next/head";
import { useEffect } from "react";

const Privacy = () => {
  useEffect(() => {
    document.querySelector("html")!.style.scrollSnapType = "none";
  }, []);
  return (
    <>
      <Head>
        <title>VSFG - Privacy & Policy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Policy />
    </>
  );
};

export default Privacy;
